site_name: mimikit
theme:
    name: readthedocs
nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - 'User Guide':
      - 'Intro to practical Deep Learning': 'user-guide/intro-deep-learning.md'
      - 'Using colab': 'user-guide/colab.md'
      - 'Make & use Databases': 'user-guide/data.md'
      - 'freqnet package': 'user-guide/freqnet.md'
      - 'Training kit': 'user-guide/kit.md'
  - 'API Reference':
      - 'data': 'api-reference/data.md'
      - 'freqnet': 'api-reference/freqnet.md'
      - 'kit': 'api-reference/kit.md'
  - 'License': 'license.md'